name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    # Runs at 4:00 AM UTC every Monday
    - cron: "0 4 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set tag date
        run: echo "TAG_DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: effectwei/nonebot2:latest,effectwei/nonebot2:${{ env.TAG_DATE }}
